[package]
name = "learn-mpm"
version = "0.1.0"
authors = ["Karthik Karanth <karanth.karthik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19.1"
nalgebra-glm = "0.10.0"